language: java
sudo: false
install: true
script: "mvn cobertura:cobertura"
script: mvn clean package -DskipTests=true

addons:
  sonarcloud:
    organization: "dawiddc-github"
    token: $SONAR_TOKEN

jdk:
  - oraclejdk8

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

after_success:
  - bash <(curl -s https://codecov.io/bash)